/**
 * Tree-sitter grammar for the Beans programming language.
 *
 * This grammar exists so Zed can highlight, outline, indent and navigate `.b`
 * files. It is deliberately a *syntax* grammar: every question that needs name
 * resolution or types is answered by `beansc lsp`, not here.
 *
 * The keyword, operator and builtin-type lists are not written here. They come
 * from `editors/shared/language.json` via `grammar-data.json`, which is
 * regenerated by `editors/scripts/generate.mjs` and drift-checked against a
 * beans checkout by `editors/scripts/sync-beans.mjs`.
 *
 * Statement termination: Beans ends statements at a newline, Go-style. This
 * grammar treats newlines as whitespace instead of modelling the lexer's
 * terminator insertion. That is safe here because Beans always brackets blocks
 * with braces and never starts a statement with an infix operator — checked
 * against every `.b` file in the beans repository by `npm run test:corpus`.
 *
 * @file Beans grammar for tree-sitter
 * @license Apache-2.0
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

const data = require('./grammar-data.json');

// Binary operator precedence, lowest binding first. Mirrors the chain of
// BINARY_LEVEL macros in beans/compiler/bootstrap/parser.cpp.
const PREC = {
  range: 1,
  or: 2,
  and: 3,
  equality: 4,
  comparison: 5,
  bitor: 6,
  bitxor: 7,
  bitand: 8,
  shift: 9,
  additive: 10,
  multiplicative: 11,
  cast: 12,
  unary: 13,
  postfix: 14,
  // `Name { ... }` is a struct literal wherever that reading actually
  // completes. In `match x as? Circle { some(c) => ... }` it does not — the
  // arms are not `field: value` — so GLR drops it and the block wins, which
  // is the call the compiler's StructGuard makes.
  struct_literal: 1,
  // A brace in expression position is a map literal only when nothing else
  // fits; `=> {}` in a match arm is an empty block, not an empty map.
  map_literal: -1,
};

const sepBy1 = (sep, rule) => seq(rule, repeat(seq(sep, rule)));
const sepBy = (sep, rule) => optional(sepBy1(sep, rule));
const commaSep1 = (rule) => sepBy1(',', rule);
const commaSep = (rule) => sepBy(',', rule);
/** A comma-separated list that tolerates a trailing comma. */
const commaList = (rule) => seq(commaSep1(rule), optional(','));

module.exports = grammar({
  name: 'beans',

  extras: ($) => [/\s/, $.line_comment, $.doc_comment, $.block_comment],

  // `async` and `await` need one token of lookahead to tell a keyword from a
  // name, which a token regex cannot express. src/scanner.c does what the
  // compiler's parser does and produces them only in the right shape.
  externals: ($) => [$.block_comment, $.async_modifier, $.await_operator],

  word: ($) => $.identifier,

  supertypes: ($) => [$._expression, $._statement, $._type, $._declaration],

  conflicts: ($) => [
    // `Name {` is a struct literal in expression position and a plain
    // expression followed by a block everywhere else. Only one of the two
    // completes, so GLR picks the right one.
    [$._expression, $.struct_literal],
    // `{` opens a map literal or a block; the closing context decides.
    [$.map_literal, $.block],
    // `util.User` is one qualified type name; `util.user` is a field access.
    // Which one it is only becomes clear at the name after the dot.
    [$._expression, $.scoped_type_identifier],
    // After `match x {`, the brace can open the arm list or a map literal that
    // belongs to the scrutinee. Only the arm reading reaches a `=>`, so GLR
    // settles it — the same call the compiler's StructGuard makes.
    // `pub align(8) x: int` is a field; `pub align(8) struct ...` is a nested
    // declaration. The name or keyword after the modifiers decides.
    [$._modifier, $.field_declaration],
  ],

  rules: {
    // A package clause comes first or not at all — the compiler rejects a
    // second one and rejects one after an import. Keeping it out of
    // `_top_level` is what makes `package` a keyword in that one position and
    // an ordinary name everywhere else.
    source_file: ($) => seq(optional($.package_declaration), repeat($._top_level)),

    // `package money`. The name is the package's own, not the last segment of
    // the path that reaches it: `shop/transport_v2/` may declare
    // `package transport`.
    package_declaration: ($) => seq('package', field('name', $.identifier)),

    _top_level: ($) => choice($.import_declaration, $._declaration),

    _declaration: ($) =>
      choice(
        $.function_declaration,
        $.class_declaration,
        $.struct_declaration,
        $.union_declaration,
        $.interface_declaration,
        $.enum_declaration,
        $.variable_declaration,
      ),

    // ---- comments ---------------------------------------------------------
    // `///` is documentation and binds to the declaration below it. `////` is
    // a divider, so it stays an ordinary line comment — same rule as the
    // compiler's lexer.
    doc_comment: (_) => token(seq('///', /[^/].*/)),
    line_comment: (_) => token(seq('//', /.*/)),
    // block_comment is an external token: `/* /* */ */` nests.

    // ---- imports ----------------------------------------------------------
    import_declaration: ($) =>
      seq(
        'import',
        field('path', $.import_path),
        optional(seq('as', field('alias', $.identifier))),
      ),

    // `std.io`, `shop.money.fx`, `github.com/acme/http`
    import_path: (_) => token(/[A-Za-z_][A-Za-z0-9_]*([./][A-Za-z0-9_.-]+)*/),

    // ---- modifiers --------------------------------------------------------
    // `pub unique class`, `pub extern "C" packed struct`, `feature "aes" fn`.
    // `unique`, `packed`, `align` and `feature` are contextual: ordinary
    // identifiers anywhere else. That is why the modifier set is narrowed per
    // declaration below rather than shared — a keyword the parser allows in a
    // position is a keyword the lexer will produce there, so `var packed: Bytes`
    // and a class field named `align` have to stay out of modifier positions.
    _modifier: ($) =>
      choice(
        $.visibility_modifier,
        $.extern_modifier,
        $.feature_modifier,
        $.align_modifier,
        $.unique_modifier,
        $.packed_modifier,
        $.opaque_modifier,
        $.static_modifier,
        $.override_modifier,
      ),

    visibility_modifier: (_) => 'pub',
    static_modifier: (_) => 'static',
    override_modifier: (_) => 'override',
    unique_modifier: (_) => 'unique',
    packed_modifier: (_) => 'packed',
    opaque_modifier: (_) => 'opaque',
    // async_modifier is an external token — see src/scanner.c. It is also
    // deliberately kept out of `_modifier`: `async` attaches to `fn` and to
    // `let`, never to `class`, `struct` or a field.
    extern_modifier: ($) => seq('extern', optional(field('abi', $.string_literal))),
    feature_modifier: ($) => seq('feature', field('feature', $.string_literal)),

    // `align` and its `(` are one token so that a field or local called
    // `align` — the compiler's own layout.b has one — still lexes as a name.
    align_modifier: ($) =>
      seq(
        alias(token(/align[ \t]*\(/), $.align_keyword),
        field('alignment', $.integer_literal),
        ')',
      ),

    // ---- functions --------------------------------------------------------
    // Greedy: the body belongs to this declaration. A body-less `fn` is an
    // interface method signature, and one is never followed by a bare block.
    function_declaration: ($) =>
      prec.right(seq(
        repeat($._modifier),
        optional($.async_modifier),
        'fn',
        field('name', $.identifier),
        optional(field('type_parameters', $.type_parameters)),
        field('parameters', $.parameter_list),
        optional(seq('->', field('return_type', $._type))),
        // `pub extern "C" fn add(...) -> i32 as "beans_wasm_add"` — the
        // exported C symbol name.
        optional(seq('as', field('export_name', $.string_literal))),
        optional(field('body', $.block)),
      )),

    parameter_list: ($) => seq('(', optional(commaList($.parameter)), ')'),

    parameter: ($) =>
      seq(
        optional(field('mode', $.parameter_mode)),
        field('name', $.identifier),
        ':',
        field('type', $._type),
      ),

    parameter_mode: (_) => choice('inout', 'move'),

    type_parameters: ($) => seq('<', commaList($.type_parameter), '>'),

    type_parameter: ($) =>
      seq(
        field('name', $.type_identifier),
        optional(seq('implements', field('bounds', $.type_bounds))),
      ),

    // `T implements A & B`
    type_bounds: ($) => sepBy1('&', $._type),

    // ---- types ------------------------------------------------------------
    class_declaration: ($) =>
      seq(
        repeat($._modifier),
        'class',
        field('name', $.type_identifier),
        optional(field('type_parameters', $.type_parameters)),
        optional(seq('extends', field('superclass', $._type))),
        optional(field('interfaces', $.implements_clause)),
        field('body', $.declaration_body),
      ),

    // A class lists its interfaces with commas: `implements Tagged, Counted`.
    // Generic bounds use `&` instead — see type_parameter.
    implements_clause: ($) => seq('implements', commaSep1($._type)),

    // `extern "C" opaque struct Handle` declares an incomplete C type, so the
    // body is optional here.
    struct_declaration: ($) =>
      prec.right(
        seq(
          repeat($._modifier),
          'struct',
          field('name', $.type_identifier),
          optional(field('type_parameters', $.type_parameters)),
          optional(field('body', $.declaration_body)),
        ),
      ),

    union_declaration: ($) =>
      prec.right(
        seq(
          repeat($._modifier),
          'union',
          field('name', $.type_identifier),
          optional(field('body', $.declaration_body)),
        ),
      ),

    interface_declaration: ($) =>
      seq(
        repeat($._modifier),
        'interface',
        field('name', $.type_identifier),
        optional(field('type_parameters', $.type_parameters)),
        optional(seq('extends', field('superclass', $.type_bounds))),
        field('body', $.declaration_body),
      ),

    declaration_body: ($) =>
      seq('{', repeat(choice($.field_declaration, $.function_declaration)), '}'),

    // A field takes `pub` and `align(N)` — nothing else, so `packed: Bytes`
    // stays a field named `packed`.
    field_declaration: ($) =>
      seq(
        optional($.visibility_modifier),
        optional($.align_modifier),
        field('name', $.identifier),
        ':',
        field('type', $._type),
        optional(seq('=', field('default', $._expression))),
      ),

    enum_declaration: ($) =>
      seq(
        repeat($._modifier),
        'enum',
        field('name', $.type_identifier),
        optional(field('type_parameters', $.type_parameters)),
        field('body', $.enum_body),
      ),

    enum_body: ($) =>
      seq(
        '{',
        repeat(seq($.enum_variant, optional(','))),
        repeat($.function_declaration),
        '}',
      ),

    enum_variant: ($) =>
      seq(field('name', $.identifier), optional(field('payload', $.parameter_list))),

    // ---- type expressions -------------------------------------------------
    _type: ($) =>
      choice(
        $.primitive_type,
        $.generic_type,
        $.type_identifier,
        $.scoped_type_identifier,
        $.function_type,
        $.array_type,
      ),

    // No token precedence here on purpose. `int` is a prefix of `interface`,
    // and raising `int` above the other keywords makes the keyword lexer stop
    // at `int` and never reach `interface`.
    primitive_type: (_) =>
      token(
        choice(...data.types.primitives, data.types.unit, new RegExp(data.types.simdTypeRegex)),
      ),

    generic_type: ($) =>
      seq(
        field('name', choice($.type_identifier, $.scoped_type_identifier)),
        field('type_arguments', $.type_arguments),
      ),

    type_arguments: ($) => seq(token(prec(1, '<')), commaSep1($._type), '>'),

    // `[i32; 4]`, `[RawPtr<u8>; 2]`
    array_type: ($) =>
      seq('[', field('element', $._type), ';', field('length', $._expression), ']'),

    function_type: ($) =>
      seq(
        'fn',
        '(',
        optional(commaList($._type)),
        ')',
        optional(seq('->', field('return_type', $._type))),
      ),

    // `util.User` — the package qualifier is a plain name, the type is capitalized.
    scoped_type_identifier: ($) =>
      seq(field('path', $.identifier), '.', field('name', $.type_identifier)),

    // Beans convention, stated in the spec: `Option` is a type, `some` is a value.
    type_identifier: (_) => token(/[A-Z][a-zA-Z0-9_]*/),

    // ---- statements -------------------------------------------------------
    block: ($) => seq('{', repeat($._statement), '}'),

    // `if` and `match` are values in Beans, so they reach statement position
    // through `expression_statement` rather than having a second rule each.
    _statement: ($) =>
      choice(
        $.variable_declaration,
        $.assignment_statement,
        $.return_statement,
        $.break_statement,
        $.continue_statement,
        $.defer_statement,
        $.for_statement,
        $.unsafe_block,
        $.expression_statement,
      ),

    // Only `pub` and `async`: a local takes no other modifier, and letting
    // more in here would make `var packed: Bytes` lex `packed` as a keyword.
    //
    // `async let x = f()` starts a child task that runs while the rest of the
    // body continues; the value arrives at the `await`. The compiler accepts
    // the pair only inside an async body, and only with `let` — never `var`.
    variable_declaration: ($) =>
      seq(
        choice(
          seq(optional($.visibility_modifier), field('kind', choice('let', 'var'))),
          // `async let` is a statement inside an async body, so it never
          // carries `pub` — and keeping the two apart is also what stops
          // `pub async` reading as the start of a function declaration.
          seq($.async_modifier, field('kind', 'let')),
        ),
        field('name', $.identifier),
        optional(seq(':', field('type', $._type))),
        optional(seq('=', field('value', $._expression))),
      ),

    assignment_statement: ($) =>
      seq(
        field('left', $._expression),
        field('operator', choice(...data.operators.assignment)),
        field('right', $._expression),
      ),

    // Greedy: `return` takes the rest of the line. Without newline tokens the
    // parser cannot otherwise tell `return (x)` from a bare `return` followed
    // by a parenthesized statement — a shape Beans code never has.
    return_statement: ($) =>
      prec.right(seq('return', optional(field('value', $._expression)))),
    break_statement: (_) => 'break',
    continue_statement: (_) => 'continue',

    defer_statement: ($) => seq('defer', field('body', choice($._expression, $.block))),

    unsafe_block: ($) => seq('unsafe', field('body', $.block)),

    // `for { }` infinite, `for cond { }` while, `for x: T in iter { }` each.
    for_statement: ($) =>
      seq(
        'for',
        optional(
          choice(
            seq(
              field('binding', $.identifier),
              ':',
              field('binding_type', $._type),
              'in',
              field('iterable', $._expression),
            ),
            field('condition', $._expression),
          ),
        ),
        field('body', $.block),
      ),

    expression_statement: ($) => $._expression,

    // ---- expressions ------------------------------------------------------
    _expression: ($) =>
      choice(
        $.identifier,
        $.type_identifier,
        $.self_expression,
        $.super_expression,
        $.integer_literal,
        $.float_literal,
        $.boolean_literal,
        $.string_literal,
        $.list_literal,
        $.map_literal,
        $.struct_literal,
        $.parenthesized_expression,
        $.unary_expression,
        $.binary_expression,
        $.range_expression,
        $.cast_expression,
        $.await_expression,
        $.call_expression,
        $.field_expression,
        $.index_expression,
        $.try_expression,
        $.new_expression,
        $.layout_expression,
        $.lambda_expression,
        $.if_expression,
        $.match_expression,
      ),

    self_expression: (_) => 'self',
    super_expression: (_) => 'super',

    parenthesized_expression: ($) => seq('(', $._expression, ')'),

    // `await handle`, `await net.await_readable(fd)`.
    //
    // Binds tighter than every binary operator and looser than call, field and
    // index, so `await a + b` is `(await a) + b` and `await f()` awaits the
    // call's result. The compiler takes a cast-level operand and then rotates
    // any `?` or `as` back above the await, which lands in the same shape.
    // The compiler also requires an async body; the scanner settles what it
    // can see instead — see src/scanner.c.
    await_expression: ($) =>
      prec.right(PREC.unary, seq($.await_operator, field('operand', $._expression))),

    // `-x`, `!ok`, `~bits`, `move out`, `inout buffer`
    unary_expression: ($) =>
      prec.right(
        PREC.unary,
        seq(
          field('operator', choice('-', '!', '~', 'move', 'take', 'inout')),
          field('operand', $._expression),
        ),
      ),

    binary_expression: ($) => {
      const levels = [
        [PREC.or, ['||']],
        [PREC.and, ['&&']],
        [PREC.equality, ['==', '!=']],
        [PREC.comparison, ['<', '<=', '>', '>=']],
        [PREC.bitor, ['|']],
        [PREC.bitxor, ['^']],
        [PREC.bitand, ['&']],
        [PREC.shift, ['<<', '>>']],
        [PREC.additive, ['+', '-']],
        [PREC.multiplicative, ['*', '/', '%']],
      ];
      return choice(
        ...levels.flatMap(([precedence, operators]) =>
          operators.map((operator) =>
            prec.left(
              precedence,
              seq(
                field('left', $._expression),
                field('operator', operator),
                field('right', $._expression),
              ),
            ),
          ),
        ),
      );
    },

    // Non-associative, above `||`, exactly like Parser::parse_expr.
    range_expression: ($) =>
      prec.left(
        PREC.range,
        seq(
          field('start', $._expression),
          field('operator', choice('..', '..=')),
          field('end', $._expression),
        ),
      ),

    // `x as int`, `g as? Counter` (checked downcast, gives Option<T>)
    cast_expression: ($) =>
      prec.left(
        PREC.cast,
        seq(
          field('value', $._expression),
          'as',
          optional(field('checked', '?')),
          field('type', $._type),
        ),
      ),

    call_expression: ($) =>
      prec(
        PREC.postfix,
        seq(field('function', $._expression), field('arguments', $.argument_list)),
      ),

    argument_list: ($) => seq('(', optional(commaList($._expression)), ')'),

    field_expression: ($) =>
      prec(
        PREC.postfix,
        seq(field('object', $._expression), '.', field('field', $.identifier)),
      ),

    index_expression: ($) =>
      prec(
        PREC.postfix,
        seq(field('object', $._expression), '[', field('index', $._expression), ']'),
      ),

    // Postfix `?`: propagate an `err`/`none` to the caller.
    try_expression: ($) => prec(PREC.postfix, seq(field('value', $._expression), '?')),

    new_expression: ($) =>
      prec.right(
        seq(
          'new',
          field('type', choice($.generic_type, $.type_identifier, $.scoped_type_identifier)),
          optional(field('arguments', $.argument_list)),
        ),
      ),

    // size_of(T) / align_of(T) / offset_of(T, field) take a *type*, so they
    // cannot be ordinary calls. Contextual: special only right before `(`.
    layout_expression: ($) =>
      seq(
        field('operator', choice(...data.contextualKeywords.typeOperators)),
        '(',
        field('type', $._type),
        optional(seq(',', field('field', $.identifier))),
        ')',
      ),

    lambda_expression: ($) =>
      seq(
        'fn',
        field('parameters', $.parameter_list),
        optional(seq('->', field('return_type', $._type))),
        field('body', $.block),
      ),

    // One rule for both jobs: a statement `if` simply has no `else`.
    if_expression: ($) =>
      prec.right(
        seq(
          'if',
          field('condition', $._expression),
          field('consequence', $.block),
          optional(seq('else', field('alternative', choice($.block, $.if_expression)))),
        ),
      ),

    match_expression: ($) =>
      seq('match', field('value', $._expression), field('body', $.match_block)),

    match_block: ($) => seq('{', repeat(seq($.match_arm, optional(','))), '}'),

    match_arm: ($) =>
      seq(field('pattern', $._pattern), '=>', field('value', choice($.block, $._expression))),

    // Patterns follow Parser::parse_pattern / parse_pattern_atom exactly:
    // literals (possibly negative, possibly a range), a name with optional
    // typed bindings, `_`, and `|` alternation. Note that a payload holds
    // *bindings*, not nested patterns.
    _pattern: ($) => choice($.or_pattern, $._pattern_atom),

    or_pattern: ($) => seq($._pattern_atom, repeat1(seq('|', $._pattern_atom))),

    _pattern_atom: ($) =>
      choice(
        $.range_pattern,
        $.literal_pattern,
        $.variant_pattern,
        $.wildcard_pattern,
        $.identifier,
      ),

    // `some(value)`, `ok(n)`, `err(e)`, `circle(r: float)`
    variant_pattern: ($) =>
      seq(
        field('name', $.identifier),
        '(',
        optional(commaList($.pattern_binding)),
        ')',
      ),

    pattern_binding: ($) =>
      seq(field('name', $.identifier), optional(seq(':', field('type', $._type)))),

    literal_pattern: ($) => $._pattern_literal,

    // `3..=9`, `-10..=0`
    range_pattern: ($) =>
      seq(
        field('start', $._pattern_literal),
        choice('..', '..='),
        field('end', $._pattern_literal),
      ),

    _pattern_literal: ($) =>
      choice(
        $.integer_literal,
        $.float_literal,
        $.string_literal,
        $.boolean_literal,
        $.negative_literal,
      ),

    negative_literal: ($) => seq('-', choice($.integer_literal, $.float_literal)),

    wildcard_pattern: (_) => '_',

    // ---- literals ---------------------------------------------------------
    list_literal: ($) => seq('[', optional(commaList($._expression)), ']'),

    map_literal: ($) =>
      prec.dynamic(
        PREC.map_literal,
        seq(
          '{',
          optional(
            commaList(seq(field('key', $._expression), ':', field('value', $._expression))),
          ),
          '}',
        ),
      ),

    struct_literal: ($) =>
      prec.dynamic(
        PREC.struct_literal,
        seq(
          field('type', choice($.generic_type, $.type_identifier, $.scoped_type_identifier)),
          field('body', $.field_initializer_list),
        ),
      ),

    field_initializer_list: ($) => seq('{', optional(commaList($.field_initializer)), '}'),

    field_initializer: ($) =>
      seq(field('name', $.identifier), ':', field('value', $._expression)),

    boolean_literal: (_) => choice('true', 'false'),

    integer_literal: (_) =>
      token(
        choice(
          /0[xX][0-9a-fA-F][0-9a-fA-F_]*/,
          /0[bB][01][01_]*/,
          /[0-9][0-9_]*/,
        ),
      ),

    // `0..10` is a range, so a fraction always needs a digit after the dot.
    float_literal: (_) =>
      token(
        choice(
          /[0-9][0-9_]*\.[0-9][0-9_]*([eE][+-]?[0-9]+)?/,
          /[0-9][0-9_]*[eE][+-]?[0-9]+/,
        ),
      ),

    // Strings interpolate: `"total {price * qty:8.2}"`. An interpolated
    // expression may itself contain strings, so this recurses.
    string_literal: ($) =>
      seq(
        '"',
        repeat(choice($.escape_sequence, $.interpolation, $._string_content)),
        '"',
      ),

    // A bare `}` is ordinary text — the lexer only ever tracks `{` depth, so
    // `"}"` and `"kind == \"}\""` are strings, not broken interpolations.
    _string_content: (_) => token.immediate(prec(1, /[^"\\{]+/)),

    escape_sequence: (_) => token.immediate(/\\[ntr0\\"{}]/),

    interpolation: ($) =>
      seq(
        token.immediate('{'),
        field('expression', $._expression),
        optional(field('format', $.format_spec)),
        '}',
      ),

    // `{x:8}`, `{x:-8}`, `{pi:.2}`, `{pi:8.2}`
    format_spec: (_) => token(seq(':', /-?[0-9]*(\.[0-9]+)?/)),

    identifier: (_) => /[a-zA-Z_][a-zA-Z0-9_]*/,
  },
});
