; Beans bracket matching for Zed
; Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.

("(" @open ")" @close)
("[" @open "]" @close)
("{" @open "}" @close)
("\"" @open "\"" @close)
