; Beans syntax highlighting for Zed
; Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.

; Comments -------------------------------------------------------------------
(line_comment) @comment
(block_comment) @comment
(doc_comment) @comment.doc

; Literals -------------------------------------------------------------------
(integer_literal) @number
(float_literal) @number
(boolean_literal) @constant.builtin
(string_literal) @string
(escape_sequence) @string.escape
(format_spec) @string.special

; An interpolated expression is code, not string text.
(interpolation
  "{" @punctuation.special
  "}" @punctuation.special)

; Types ----------------------------------------------------------------------
(primitive_type) @type.builtin
(type_identifier) @type
(scoped_type_identifier (identifier) @namespace)
(type_parameter name: (type_identifier) @type.parameter)

; Builtin types are ordinary capitalized names in the grammar, so they are
; matched by value rather than by node type.
((type_identifier) @type.builtin
  (#any-of? @type.builtin
    "List"
    "Map"
    "OrderedMap"
    "Thread"
    "Mutex"
    "Channel"
    "Box"
    "Arena"
    "Shared"
    "Weak"
    "RawPtr"
    "Slice"
    "Atomic"
    "StoredCallback"
    "Bytes"
    "File"
    "Dir"
    "MMap"
    "Error"
    "Option"
    "Result"
    "AtomicInt"
    "CpuFeature"
    "RoundingMode"
    "MemoryOrder"))

; Declarations ---------------------------------------------------------------
(function_declaration name: (identifier) @function.definition)
(lambda_expression "fn" @keyword)
(parameter name: (identifier) @variable.parameter)
(field_declaration name: (identifier) @property)
(field_initializer name: (identifier) @property)
(enum_variant name: (identifier) @constant)
(variable_declaration name: (identifier) @variable)

(class_declaration name: (type_identifier) @type.definition)
(struct_declaration name: (type_identifier) @type.definition)
(union_declaration name: (type_identifier) @type.definition)
(interface_declaration name: (type_identifier) @type.definition)
(enum_declaration name: (type_identifier) @type.definition)

; Uses -----------------------------------------------------------------------
(call_expression
  function: (identifier) @function)
(call_expression
  function: (field_expression field: (identifier) @function.method))
(field_expression field: (identifier) @property)
(variant_pattern name: (identifier) @constructor)

(import_declaration path: (import_path) @string.special.path)
(import_declaration alias: (identifier) @namespace)

; The package clause names the package itself, so it reads like an import.
(package_declaration "package" @keyword.import)
(package_declaration name: (identifier) @namespace)

(layout_expression operator: _ @function.builtin)

; Keywords -------------------------------------------------------------------
[
  "class"
  "struct"
  "union"
  "interface"
  "enum"
  "fn"
  "let"
  "var"
] @keyword

[
  "if"
  "else"
  "for"
  "in"
  "match"
  "return"
  "defer"
] @keyword
(break_statement) @keyword
(continue_statement) @keyword

[
  "extern"
  "unsafe"
  "move"
  "take"
  "inout"
] @keyword.modifier
(visibility_modifier) @keyword.modifier
(override_modifier) @keyword.modifier
(static_modifier) @keyword.modifier

[
  "extends"
  "implements"
] @keyword.modifier

[
  "as"
  "new"
] @keyword.operator

[
  "import"
] @keyword.import


(self_expression) @variable.special
(super_expression) @variable.special

; Contextual modifiers: highlighted only where the compiler treats them as
; modifiers. Everywhere else they are ordinary identifiers.
[
  "feature"
] @keyword.modifier
(unique_modifier) @keyword.modifier
(packed_modifier) @keyword.modifier
(opaque_modifier) @keyword.modifier
(async_modifier) @keyword.modifier

(align_modifier (align_keyword) @keyword.modifier)

; await is a prefix operator on an expression, so it takes the same capture as
; the other operator-like keywords, as and new, rather than a coroutine capture
; that no theme is required to know.
(await_operator) @keyword.operator

; Operators and punctuation --------------------------------------------------
[
  "="
  "+="
  "-="
  "*="
  "/="
  "%="
  "=="
  "!="
  "<="
  ">="
  "<"
  ">"
  "&&"
  "||"
  "!"
  "+"
  "-"
  "*"
  "/"
  "%"
  "&"
  "|"
  "^"
  "~"
  "<<"
  ">>"
  "..="
  ".."
] @operator

[
  "."
  ","
  ":"
  ";"
  "?"
  "=>"
  "->"
] @punctuation.delimiter

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

; Fallback: a bare identifier is a variable.
(identifier) @variable
