; Beans code outline for Zed
; Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.

(function_declaration
  (visibility_modifier)? @context
  (static_modifier)? @context
  (override_modifier)? @context
  "fn" @context
  name: (identifier) @name) @item

(const_declaration
  (visibility_modifier)? @context
  "const" @context
  name: (identifier) @name) @item

(class_declaration
  (visibility_modifier)? @context
  (unique_modifier)? @context
  "class" @context
  name: (type_identifier) @name) @item

(struct_declaration
  (visibility_modifier)? @context
  "struct" @context
  name: (type_identifier) @name) @item

(union_declaration
  (visibility_modifier)? @context
  "union" @context
  name: (type_identifier) @name) @item

(interface_declaration
  (visibility_modifier)? @context
  "interface" @context
  name: (type_identifier) @name) @item

(enum_declaration
  (visibility_modifier)? @context
  "enum" @context
  name: (type_identifier) @name) @item

(field_declaration
  name: (identifier) @name) @item

(enum_variant
  name: (identifier) @name) @item

(doc_comment)+ @annotation
