; Beans text objects for Zed
; Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.

(function_declaration
  body: (_) @function.inside) @function.around

(lambda_expression
  body: (_) @function.inside) @function.around

(class_declaration
  body: (_) @class.inside) @class.around

(struct_declaration
  body: (_) @class.inside) @class.around

(interface_declaration
  body: (_) @class.inside) @class.around

(enum_declaration
  body: (_) @class.inside) @class.around

(line_comment) @comment.around
(doc_comment) @comment.around
(block_comment) @comment.around

(parameter) @parameter.inside
(argument_list (_) @parameter.inside)
