// Loads editors/shared/language.json — the one place editor-side Beans
// language facts are written down — and exposes the derived lists the
// generators need.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

/** Repository root: editors/ */
export const editorsRoot = resolve(here, '..', '..');

export const sharedPath = join(editorsRoot, 'shared', 'language.json');

export function loadLanguageData(path = sharedPath) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

/** Every reserved keyword, sorted longest-first so alternations match greedily. */
export function keywordsLongestFirst(data) {
  return [...data.keywords.reserved].sort((a, b) => b.length - a.length || a.localeCompare(b));
}

/** All contextual keywords in one flat list. */
export function contextualKeywords(data) {
  const c = data.contextualKeywords;
  return [
    ...c.modifiers, ...c.variables, ...c.typeOperators,
    ...c.declarations, ...c.expressionOperators,
  ];
}

/** Every builtin type name (primitives excluded). */
export function builtinTypeNames(data) {
  const t = data.types;
  return [...t.genericClasses, ...t.builtinClasses, ...t.builtinEnums];
}

/**
 * Every operator spelling, longest first. Tree-sitter and TextMate both need
 * longest-match order or `<` would shadow `<<` and `<=`.
 */
export function operatorsLongestFirst(data) {
  const o = data.operators;
  const all = [
    ...o.assignment, ...o.comparison, ...o.logical, ...o.arithmetic,
    ...o.bitwise, ...o.range, ...o.arrow,
  ];
  return [...new Set(all)].sort((a, b) => b.length - a.length || a.localeCompare(b));
}

/** Escape a string for use inside a regular expression. */
export function reEscape(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** A `\b`-anchored alternation over a word list. */
export function wordAlternation(words) {
  return `\\b(?:${[...words].sort((a, b) => b.length - a.length || a.localeCompare(b)).map(reEscape).join('|')})\\b`;
}

export const GENERATED_BANNER =
  'Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.';
