; Beans auto-indentation for Zed
; Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.

(block) @indent
(declaration_body) @indent
(enum_body) @indent
(match_block) @indent
(field_initializer_list) @indent
(map_literal) @indent
(list_literal) @indent
(argument_list) @indent
(parameter_list) @indent

[
  "}"
  ")"
  "]"
] @end
