; Beans language injections for Zed
; Generated by editors/scripts/generate.mjs from editors/shared/language.json. Do not edit by hand.

; Inline assembly templates are assembly, not Beans strings.
((call_expression
   function: (field_expression field: (identifier) @_name)
   arguments: (argument_list . (string_literal) @injection.content))
 (#eq? @_name "value")
 (#set! injection.language "asm"))
